
services:
  database:
    container_name: database
    image: postgres:latest
    restart: always
    env_file:
      - config.env
    ports:
      - "54320:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "8888:8888"
    env_file:
      - config.env
    environment:
      - DB_HOST=database
      - DB_PORT=5432